--------------------------------------------------------
--  File created - Monday-September-23-2013   
--------------------------------------------------------
DROP TABLE "USERSESSIONS"."SESSIONS";
--------------------------------------------------------
--  DDL for Table SESSIONS
--------------------------------------------------------

  CREATE TABLE "USERSESSIONS"."SESSIONS" 
   (	"SESSION_ID" VARCHAR2(255 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"EXPIRY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USERSESSIONS.SESSIONS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index USERSESSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERSESSIONS"."USERSESSION_PK" ON "USERSESSIONS"."SESSIONS" ("SESSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SESSIONS
--------------------------------------------------------

  ALTER TABLE "USERSESSIONS"."SESSIONS" ADD CONSTRAINT "USERSESSION_PK" PRIMARY KEY ("SESSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USERSESSIONS"."SESSIONS" MODIFY ("SESSION_ID" NOT NULL ENABLE);
